/**
*___________________________________________________
*@Name:     CDM_UtilConst
*@Author:   Chandra Kanchi
*@Created:  June 26, 2020
*@Used_By:  Global 
*___________________________________________________
*@Description: This class has been used for Static Utils Class.
*___________________________________________________
*@Changes: 
* MM-DD-YYY. Explanation of the change.
**/

global with sharing class CDM_UtilConst {
    public static String RC = 'RC';
    public static String SG = 'SG';
    public static String SD = 'SD';
    public static String Credit_Note = 'Credit_Note';
    public static String Debit_Note = 'Debit_Note';
    public static String CreditNote = 'Credit Note';
    public static String DebitNote = 'Debit Note';
   // public static String SD = 'SD';

}