/**
* @author      Avinash Jain
* @date      20/08/2019
* @description    Contains all the constant values used in GCP_TFD project(BP Conga)      
*/
public With Sharing class GCP_TFD_Constant
{
	Public static string Queue = 'Queue';
    Public static String Yes ='Yes';
    Public static String SBLC = 'SBLC';
    Public static String Insurance = 'Insurance';
    Public static String Guarantee = 'Guarantee';
    Public static String open = 'open';
    Public static String OCP = 'OCP';
    Public static String GcpImport = 'Import';
    Public static String GenerateSchedule = 'Generate Schedule 1 for ';
    Public static String GOA = 'GOA';
    Public static String U = 'U';
    Public static String E = 'E';
    Public static String A = 'A';
    Public static String GOE = 'GOE';
    Public static String GOEH = 'GOEH';
    Public static String closed = 'closed';
    Public static String DocGen = 'Document generated';
    public static final string PARCEL_STATUS_CLAIMED = 'Claimed';
    public static final string PARCEL_STATUS_NEW = 'New';
    public static final string PARCEL_STATUS_CLAIM_CANCELLED = 'Claim Cancelled';
    public static final string LC_RECORD_TYPE_NAME = 'LC Claim Request'; 
    public static final string BPLE_RECORD_TYPE_NAME = 'GCP ETY BPLE'; 
    public static final string CPARTY_RECORD_TYPE_NAME = 'GCP ETY Counterparty'; 
    public static final string LC_TYPE_EXPORT = 'Export';    
    public static final string BPG_DISABLE_ALL = 'BPG_DisableAll';
    public static final string CASE_STATUS_IN_NEGOTIATION = 'In Negotiation';
    public static final string CASE_STATUS_SENT_FOR_EXT_SIGNATURE = 'Sent for external signature';
    public static final string CASE_RECORD_TYPE_IMPORT_LC = 'Import LC';
    public static final string CASE_RECORD_TYPE_EXPORT_LC = 'Export LC Claim';
    public static final string CE_RECORD_TYPE_BPLE = 'GCP ETY BPLE';
    public static final string CE_RECORD_TYPE_COUNTERPARTY = 'GCP ETY Counterparty';
}